# Generated by Django 3.0.2 on 2020-04-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, default='', null=True)),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('dialog', models.TextField(default='start')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('temp', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.Account')),
            ],
        ),
    ]
