# Generated by Django 3.0.2 on 2021-01-17 19:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210117_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('model_group_id', models.IntegerField()),
                ('model_code', models.TextField()),
                ('min_price', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
                ('versions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TGAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(app.models.Account, models.Model),
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
