# Generated by Django 3.0.2 on 2021-01-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210117_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKAccount',
            fields=[
                ('tgaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.TGAccount')),
            ],
            bases=('app.tgaccount',),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='dialog',
            field=models.TextField(default='start'),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='first_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='last_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='temp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='username',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='vin',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
