# Generated by Django 3.0.2 on 2021-02-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210208_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgaccount',
            name='dialog',
            field=models.TextField(default='start'),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='first_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='last_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='temp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='username',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='vin',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
