# Generated by Django 3.0.2 on 2021-03-17 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('model_group_id', models.IntegerField()),
                ('model_code', models.TextField()),
                ('year', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
                ('versions', models.TextField()),
                ('photo', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('street', models.TextField()),
                ('zip', models.IntegerField()),
                ('city', models.TextField()),
                ('phone', models.TextField(null=True)),
                ('helios_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='Контент')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Выключить отображение')),
            ],
            options={
                'verbose_name': 'спец. прогр.',
                'verbose_name_plural': 'Спец. программы',
            },
        ),
        migrations.CreateModel(
            name='TGAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, default='', null=True)),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('dialog', models.TextField(default='start')),
                ('vin', models.TextField(blank=True, default=None, null=True)),
                ('mailing', models.BooleanField(default=True)),
                ('temp', models.TextField(blank=True, default='')),
                ('parking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Parking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='Контент')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.SpecialCategory', verbose_name='Спец. программа')),
            ],
            options={
                'verbose_name': 'элемент спец. программы',
                'verbose_name_plural': 'Элементы спец. программ',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_tg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='app.TGAccount')),
            ],
        ),
    ]
