# Generated by Django 3.0.2 on 2021-03-30 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.Car')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.Dealer')),
                ('user_tg', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.TGAccount')),
            ],
        ),
    ]
