# Generated by Django 3.0.2 on 2021-03-30 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='testdrive',
            options={'verbose_name': 'тест-драйв', 'verbose_name_plural': 'Заявки на тест-драйв'},
        ),
        migrations.AlterModelOptions(
            name='tgaccount',
            options={'verbose_name': 'аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='service',
            name='api_id',
            field=models.IntegerField(verbose_name='Айди API'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.Dealer', verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='user_tg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_tickets', to='app.TGAccount', verbose_name='Telegram пользователь'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='dialog',
            field=models.TextField(default='start', verbose_name='Системный диалог'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='first_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='last_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='mailing',
            field=models.BooleanField(default=True, verbose_name='Подписка на рассылку'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='parking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Parking', verbose_name='Паркинг'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='temp',
            field=models.TextField(blank=True, default='', verbose_name='Временные данные'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='username',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='vin',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='VIN'),
        ),
    ]
