# Generated by Django 3.0.2 on 2021-04-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vkaccoun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VKAccoun',
            new_name='VKAccount',
        ),
    ]
