# Generated by Django 3.0.2 on 2021-05-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210412_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(blank=True, default='', null=True, verbose_name='Фамилия')),
                ('username', models.TextField(blank=True, default=None, null=True, verbose_name='Логин')),
                ('dialog', models.TextField(default='start', verbose_name='Системный диалог')),
                ('vin', models.TextField(blank=True, default=None, null=True, verbose_name='VIN')),
                ('mailing', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
                ('temp', models.TextField(blank=True, default='', verbose_name='Временные данные')),
                ('parking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Parking', verbose_name='Паркинг')),
            ],
            options={
                'verbose_name': 'фб аккаунт',
                'verbose_name_plural': 'ФБ Аккаунты',
            },
        ),
    ]
