# Generated by Django 3.0.2 on 2021-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fbaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbaccount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vkaccount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
