# Generated by Django 3.0.2 on 2021-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='vin',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
