# Generated by Django 3.0.2 on 2021-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210208_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgaccount',
            name='mailing',
            field=models.BooleanField(default=True),
        ),
    ]
