# Generated by Django 3.0.2 on 2021-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_specialcategory_specialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcategory',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
