# Generated by Django 3.0.2 on 2021-03-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_specialcategory_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=32)),
                ('street', models.TextField()),
                ('zip', models.IntegerField()),
                ('city', models.TextField()),
                ('phone', models.IntegerField()),
                ('helios_code', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='specialcategory',
            options={'verbose_name': 'спец. прогр.', 'verbose_name_plural': 'Спец. программы'},
        ),
        migrations.AlterModelOptions(
            name='specialitem',
            options={'verbose_name': 'элемент спец. программы', 'verbose_name_plural': 'Элементы спец. программ'},
        ),
        migrations.AlterField(
            model_name='specialcategory',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Выключить отображение'),
        ),
        migrations.AlterField(
            model_name='specialcategory',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialcategory',
            name='text',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.SpecialCategory', verbose_name='Спец. программа'),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='text',
            field=models.TextField(verbose_name='Контент'),
        ),
    ]
